[build]
# Use a CI-friendly build that avoids Turbopack (not supported on Netlify build bots yet)
command = "npm run build:ci"
publish = ".next"

[build.environment]
# Ensure a modern LTS Node.js version compatible with Next.js 15/React 19
NODE_VERSION = "20"

[[plugins]]
# Official Next.js adapter for Netlify
package = "@netlify/plugin-nextjs"
