services:
  - type: web
    name: amogh-portfolio
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:render
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
