services:
  - type: web
    name: portfolio
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
      - key: HOSTNAME
        value: 0.0.0.0
